services:
  traj-opt:
    build: .
    platform: linux/amd64
    container_name: traj-opt-sandbox
    volumes:
      - ./src:/app/src
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - TRAJOPT_LOG_THRESH=DEBUG
    network_mode: host
    stdin_open: true
    tty: true
    privileged: true
